version: "3"

services:
  db:
    container_name: postgres_db
    image: postgres:12.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  django:
    container_name: django
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash entrypoint.sh
    volumes:
      - ./backend:/star-burger/backend
      - ./backend/media:/star-burger/backend/media
      - ./backend/static:/star-burger/backend/staticfiles
    environment:
      API_KEY_GEOCODER: ${API_KEY_GEOCODER}
      ROLLBAR_TOKEN: ${ROLLBAR_TOKEN}
      ROLLBAR_INVIRONMENT: ${ROLLBAR_INVIRONMENT}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      DATABASE_URL: ${POSTGRES_DB_URL}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - db
      - frontend

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/bundles-src/:/frontend/bundles-src/
      - ./backend/bundles/:/frontend/bundles/
    command: ./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"

volumes:
  db_data:
  staticfiles:
  media:
  frontend:
