# Generated by Django 3.2.15 on 2024-10-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_delete_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='адрес доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='firstname',
            field=models.CharField(default='-', max_length=200, verbose_name='имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='lastname',
            field=models.CharField(blank=True, max_length=200, verbose_name='фамилия'),
        ),
    ]
