# Generated by Django 3.2.15 on 2024-10-30 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20241019_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('IN_CASH', 'Наличностью'), ('ELECTRONICLLY', 'Электронно')], db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='время регистрации'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UNPROCESSED', 'Необработанный'), ('ASSEMBLY', 'Сборка'), ('DELIVERY', 'Доставка'), ('COMPLETED', 'Выполнен')], db_index=True, default='UNPROCESSED', max_length=11, verbose_name='статус заказа'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
