# Generated by Django 3.2.15 on 2024-10-30 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocoords', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geocoords',
            options={'verbose_name': 'координаты', 'verbose_name_plural': 'координаты'},
        ),
    ]
