# Generated by Django 3.2.15 on 2024-10-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
