services:
  db:
    container_name: postgres_db
    image: postgres:12.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    restart: unless-stopped

  django:
    container_name: django
    build:
      context: ..
      dockerfile: Dockerfile
    command: bash stage/entrypoint.sh
    volumes:
      - ..:/star-burger
      - ../media:/star-burger/media
      - ../static:/star-burger/staticfiles
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      DATABASE_URL: ${POSTGRES_DB_URL}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    ports:
      - 8000:8000
    depends_on:
      - db
      - frontend
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/bundles-src/:/frontend/bundles-src/
      - ../bundles/:/frontend/bundles/
    command: ./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"
    restart: unless-stopped

volumes:
  db_data:
  staticfiles:
  media:
  frontend:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
