version: "3.9"

services:
  db:
    container_name: postgres_db
    image: postgres:12.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  django:
    container_name: django
    build:
      context: ..
      dockerfile: Dockerfile
    command: bash entrypoint.sh
    volumes:
      - ..:/star-burger
      - ../media:/star-burger/media
      - ../static:/star-burger/staticfiles
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      DATABASE_URL: ${POSTGRES_DB_URL}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - db
      - frontend

  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/bundles-src/:/frontend/bundles-src/
      - ../bundles/:/frontend/bundles/
    command: ./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"

volumes:
  db_data:
  staticfiles:
  media:
  frontend:
